### ISSUE TITLE
SerializableException: The system cannot find the file specified

### ISSUE THREAD

**Issue by Narutofox** [axodox/AxoCover#164]
Versions:

VS 2017 Community 15.7.1
AxoCover 1.1.6.14

Issue:
```
Test execution started.
Test execution failed.
SerializableException: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at AxoCover.Common.ProcessHost.ServiceProcess..ctor(IProcessInfo processInfo) in C:\projects\axotools\AxoCover.Common\ProcessHost\ServiceProcess.cs:line 54
   at AxoCover.Models.Testing.TestProcess`1..ctor(IProcessInfo processInfo, IOptions options) in C:\projects\axotools\AxoCover\Models\Testing\TestProcess.cs:line 28
   at AxoCover.Models.Testing.Execution.ExecutionProcess..ctor(IHostProcessInfo hostProcess, String[] testPlatformAssemblies, IOptions options) in C:\projects\axotools\AxoCover\Models\Testing\Execution\ExecutionProcess.cs:line 20
   at AxoCover.Models.Testing.Execution.ExecutionProcess.Create(String[] testPlatformAssemblies, IHostProcessInfo hostProcess, IOptions options) in C:\projects\axotools\AxoCover\Models\Testing\Execution\ExecutionProcess.cs:line 26
   at AxoCover.Models.Testing.Execution.AxoTestRunner.RunTests(TestItem testItem, Boolean isCovering, Boolean isDebugging) in C:\projects\axotools\AxoCover\Models\Testing\Execution\AxoTestRunner.cs:line 90
   at AxoCover.Models.Testing.Execution.TestRunner.<>c__DisplayClass31_0.<RunTestsAsync>b__0() in C:\projects\axotools\AxoCover\Models\Testing\Execution\TestRunner.cs:line 51
```
This happens when I try to do Cover tests. 
Run and debug tests work normally.

**Comment by Narutofox** [comment]
Thx for the suggestion but I still get the same result.

**Comment by axodox** [comment]
Are you using default settings in AxoCover? Otherwise if there is no strange setting we need to debug the code.

**Comment by Narutofox** [comment]
Yes i think I am using default settings when problem first occurred I reinstalled AxoCover hoping it would fix it but it didn't, I didn't change settings since.

**Comment by luturol** [comment]
Hi,
I've been had the same problem with axocover and it was fixed when updating to release 1.1.7
My VS current version is 2017 15.9.11

Sometimes happend again, then I just reopen VS to solve.

Don't know why it happens. Maybe it's beacause your code versioner is deleting the .axocover folder in the repository folders?
