### ISSUE TITLE
AxoCover for VS2019

### ISSUE THREAD

**Issue by arunkarthicksr** [axodox/AxoCover#197]
Please let us know when can we expect AxoCover extension for VS 2019

**Comment by kjetilroe** [comment]
After installing the AxoCover extersion on VS 2019, I get the message that this extension will not be compatible with future version of VS, because "Synchronously autoloaded extensions will not be supported". I guess it needs to be changed to load asynchronously.

**Comment by gsGabriel** [comment]
Waiting for this

**Comment by kjetilroe** [comment]
I have uploaded my compiled vsix to dropbox: https://www.dropbox.com/s/1s8oodc4rm3f8fc/AxoCover.vsix?dl=0

It seems to be working fine for 2019 with me. Only issue is the yellow bar on the top upon startup, saying that it will not be compatible with future versions of VS.

**Comment by Malivil** [comment]
The VSIX does run in VS2019 but I have noticed that MSTestV1 tests aren't detected.
If you upgrade a solution to use MSTestV2 then the tests appear to show up fine

**Comment by tb-mtg** [comment]
Is there any update on this?

**Comment by hieuxlu** [comment]
See #191. Latest pre-release works fine for me, after VS issues warning of deprecated "Async loading" API that still need further work https://github.com/axodox/AxoCover/releases/tag/master-1.1.400

**Comment by bmcclint15** [comment]
Anyone know if this project is still active?  I was able to get this to build and work with VS19 but not sure of a PR is of any value if the effort is no longer active.  I dig it...it works...

**Comment by afelinczak** [comment]
@bmcclint15 maybe you can fork code and upload compiled extension ?
At the moment there is no free & mature working solution for code coverage in VS Community

**Comment by mendozajay** [comment]
I was trying to install axocover in vs 2019 community edition. I got this error. 

6/25/2021 11:26:25 AM - Microsoft VSIX Installer
6/25/2021 11:26:25 AM - -------------------------------------------
6/25/2021 11:26:25 AM - vsixinstaller.exe version:
6/25/2021 11:26:25 AM - 16.9.1050
6/25/2021 11:26:25 AM - -------------------------------------------
6/25/2021 11:26:25 AM - Command line parameters:
6/25/2021 11:26:25 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ArjayMendoza\Downloads\AxoCover.vsix
6/25/2021 11:26:25 AM - -------------------------------------------
6/25/2021 11:26:25 AM - Microsoft VSIX Installer
6/25/2021 11:26:25 AM - -------------------------------------------
6/25/2021 11:26:26 AM - Initializing Install...
6/25/2021 11:26:27 AM - Extension Details...
6/25/2021 11:26:27 AM - 	Identifier         : 26901782-38e1-48d4-94e9-557d44db052e
6/25/2021 11:26:27 AM - 	Name               : AxoCover
6/25/2021 11:26:27 AM - 	Author             : Péter Major
6/25/2021 11:26:27 AM - 	Version            : 1.1.7.0
6/25/2021 11:26:27 AM - 	Description        : Nice and free .Net code coverage support for Visual Studio with OpenCover.
6/25/2021 11:26:27 AM - 	Locale             : en-US
6/25/2021 11:26:27 AM - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=axodox1.AxoCover
6/25/2021 11:26:27 AM - 	InstalledByMSI     : False
6/25/2021 11:26:27 AM - 	SupportedFrameworkVersionRange : [4.5,)
6/25/2021 11:26:27 AM - 
6/25/2021 11:26:27 AM - 	SignatureState     : Unsigned
6/25/2021 11:26:27 AM - 	Supported Products : 
6/25/2021 11:26:27 AM - 		Microsoft.VisualStudio.Premium
6/25/2021 11:26:27 AM - 			Version : [11.0,15.0)
6/25/2021 11:26:27 AM - 		Microsoft.VisualStudio.Pro
6/25/2021 11:26:27 AM - 			Version : [11.0,16.0)
6/25/2021 11:26:27 AM - 		Microsoft.VisualStudio.Ultimate
6/25/2021 11:26:27 AM - 			Version : [11.0,15.0)
6/25/2021 11:26:27 AM - 		Microsoft.VisualStudio.Enterprise
6/25/2021 11:26:27 AM - 			Version : [14.0,16.0)
6/25/2021 11:26:27 AM - 		Microsoft.VisualStudio.Community
6/25/2021 11:26:27 AM - 			Version : [14.0,16.0)
6/25/2021 11:26:27 AM - 
6/25/2021 11:26:27 AM - 	References         : 
6/25/2021 11:26:27 AM - 		-------------------------------------------------------
6/25/2021 11:26:27 AM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
6/25/2021 11:26:27 AM - 		Name         : Visual Studio MPF 11.0
6/25/2021 11:26:27 AM - 		Version      : [11.0]
6/25/2021 11:26:27 AM - 		MoreInfoURL  : 
6/25/2021 11:26:27 AM - 		Nested       : No
6/25/2021 11:26:27 AM - 
6/25/2021 11:26:27 AM - 	Prerequisites      : 
6/25/2021 11:26:27 AM - 		-------------------------------------------------------
6/25/2021 11:26:27 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/25/2021 11:26:27 AM - 		Name         : Microsoft.VisualStudio.Component.CoreEditor
6/25/2021 11:26:27 AM - 		Version      : [15.0,16.0)
6/25/2021 11:26:27 AM - 
6/25/2021 11:26:27 AM - Signature Details...
6/25/2021 11:26:27 AM - 	Extension is not signed.
6/25/2021 11:26:27 AM - 
6/25/2021 11:26:27 AM - Searching for applicable products...
6/25/2021 11:26:27 AM - Found installed product - Global Location
6/25/2021 11:26:27 AM - Found installed product - Visual Studio Community 2019
6/25/2021 11:26:27 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
